# This is a basic workflow to help you get started with Actions

name: Docker Actions

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main , hello-world]
  pull_request:
    types: [labeled]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: hello-action
        uses: ./.github/actions/hello-action
        with:
          firstGreeting: "Learning Lab User"
      
      - name: external-API
        uses: ./.github/actions/cat-facts
